namespace Core.Data;

// The core tables as EF entities (PLATFORM_CORE v1.14 §4.1, 4.2, 4.5, 4.8, 5, 7). Mapping only — the
// schema itself is SQL (src/Migrations/Sql). Every key and timestamp is set by the application:
// keys with Guid.CreateVersion7(), timestamps as UTC DateTime (§2). Nothing is generated by the
// database or by EF (CoreDbContext maps every property ValueGeneratedNever; Test 28).

public sealed class Tenant
{
    public Guid Id { get; set; }
    public string Name { get; set; } = "";
    public string Status { get; set; } = "";
    public DateTime CreatedAt { get; set; }
}

public sealed class Person
{
    public Guid Id { get; set; }
    public string FullName { get; set; } = "";
    public string Email { get; set; } = "";
    public string? PhoneE164 { get; set; }
    public DateTime CreatedAt { get; set; }
}

public sealed class User
{
    public Guid Id { get; set; }
    public Guid PersonId { get; set; }
    public string UserType { get; set; } = "";
    public string Username { get; set; } = "";
    public string Status { get; set; } = "";
    public string? Language { get; set; }
    public string? Theme { get; set; }
    public DateTime? LastLoginAt { get; set; }
}

public sealed class UserPasswordCredential
{
    public Guid UserId { get; set; }
    public string PasswordHash { get; set; } = "";
    public DateTime UpdatedAt { get; set; }
}

public sealed class Membership
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid UserId { get; set; }
    public string Status { get; set; } = "";
    public DateTime CreatedAt { get; set; }
}

public sealed class MembershipRole
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid MembershipId { get; set; }
    public Guid RoleId { get; set; }
}

public sealed class Invitation
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public string Email { get; set; } = "";
    public Guid RoleId { get; set; }
    public string TokenHash { get; set; } = "";
    public string Status { get; set; } = "";
    public Guid InvitedBy { get; set; }
    public DateTime ExpiresAt { get; set; }
    public DateTime CreatedAt { get; set; }
    public string IntendedScopeMode { get; set; } = "";
}

public sealed class AuthAttempt
{
    public Guid Id { get; set; }
    public string UsernameEntered { get; set; } = "";
    public string? IpAddress { get; set; }
    public bool Succeeded { get; set; }
    public DateTime CreatedAt { get; set; }
}

public sealed class MembershipScope
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid MembershipId { get; set; }
    public string ScopeMode { get; set; } = "";
    // (v1.15) No updated_by / updated_at: the audit log attributes every change (§4.1, 7).
}

public sealed class ScopeAssignment
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid MembershipId { get; set; }
    public Guid ScopeRefId { get; set; }
    public string AssignmentRole { get; set; } = "";
    public bool Active { get; set; }
    // (v1.15) No granted_by / granted_at: the audit log attributes every change (§4.1, 7).
    public string? Reason { get; set; }
}

public sealed class MembershipAuth
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid MembershipId { get; set; }
    public string Provider { get; set; } = "";
    public string? ProviderConfig { get; set; }
}

public sealed class Module
{
    public Guid Id { get; set; }
    public string Code { get; set; } = "";
    public string NameAr { get; set; } = "";
    public string NameEn { get; set; } = "";
    public string? Icon { get; set; }
    public int DisplayOrder { get; set; }
    public bool IsActive { get; set; }
}

public sealed class Permission
{
    public Guid Id { get; set; }
    public Guid ModuleId { get; set; }
    public string Code { get; set; } = "";
    public string NameAr { get; set; } = "";
    public string NameEn { get; set; } = "";
}

public sealed class TenantModule
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid ModuleId { get; set; }
    public bool IsActive { get; set; }
    public DateTime? ActivatedAt { get; set; }
}

public sealed class Role
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public string Code { get; set; } = "";
    public string NameAr { get; set; } = "";
    public string NameEn { get; set; } = "";
    public bool IsSystem { get; set; }
    public bool IsActive { get; set; }
}

public sealed class RolePermission
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid RoleId { get; set; }
    public Guid PermissionId { get; set; }
}

public sealed class RoleTemplate
{
    public Guid Id { get; set; }
    public string Code { get; set; } = "";
    public string NameAr { get; set; } = "";
    public string NameEn { get; set; } = "";
}

public sealed class RoleTemplatePermission
{
    public Guid TemplateId { get; set; }
    public Guid PermissionId { get; set; }
}

public sealed class AuditEntry
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid? ActorId { get; set; }
    public string ActorType { get; set; } = "";
    public string Action { get; set; } = "";
    public string EntityType { get; set; } = "";
    public Guid? EntityId { get; set; }
    public string? OldValue { get; set; }
    public string? NewValue { get; set; }
    public string? IpAddress { get; set; }
    public DateTime CreatedAt { get; set; }
}
