-- T2, layer 2 — row-level security and every policy (PLATFORM_CORE v1.14).
-- Generated by extraction from docs/PLATFORM_CORE_v1_14_FROZEN_EN.md, not typed:
-- every CREATE POLICY on a concrete table, verbatim, plus the §3.1 tenant_isolation
-- template on the four manifest tables that list it explicitly (§3.6, Check 2;
-- roles per §5: "SELECT is left to tenant_isolation alone").
-- 19 tables, 57 policies. All tables are in the manifest (§3.6).

-- ENABLE + FORCE on every table in public (§3.1; Checks 1 and 5).
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
ALTER TABLE persons ENABLE ROW LEVEL SECURITY;
ALTER TABLE persons FORCE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;
ALTER TABLE user_password_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_password_credentials FORCE ROW LEVEL SECURITY;
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships FORCE ROW LEVEL SECURITY;
ALTER TABLE membership_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership_roles FORCE ROW LEVEL SECURITY;
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitations FORCE ROW LEVEL SECURITY;
ALTER TABLE auth_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_attempts FORCE ROW LEVEL SECURITY;
ALTER TABLE membership_scope ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership_scope FORCE ROW LEVEL SECURITY;
ALTER TABLE scope_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE scope_assignments FORCE ROW LEVEL SECURITY;
ALTER TABLE membership_auth ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership_auth FORCE ROW LEVEL SECURITY;
ALTER TABLE modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE modules FORCE ROW LEVEL SECURITY;
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_modules FORCE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles FORCE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions FORCE ROW LEVEL SECURITY;
ALTER TABLE role_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_templates FORCE ROW LEVEL SECURITY;
ALTER TABLE role_template_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_template_permissions FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log FORCE ROW LEVEL SECURITY;

-- The §3.1 template, listed explicitly on roles, membership_roles, tenant_modules, role_permissions.
CREATE POLICY tenant_isolation ON roles
  FOR ALL TO app_user
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid))
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY tenant_isolation ON membership_roles
  FOR ALL TO app_user
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid))
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY tenant_isolation ON tenant_modules
  FOR ALL TO app_user
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid))
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY tenant_isolation ON role_permissions
  FOR ALL TO app_user
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid))
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

-- ===== tenants
CREATE POLICY tenants_provisioner_insert ON tenants
  FOR INSERT TO provisioner
  WITH CHECK (id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY tenant_visible_to_member ON tenants
  FOR SELECT TO app_user
  USING (EXISTS (
    SELECT 1 FROM memberships m
    WHERE m.tenant_id = tenants.id
      AND m.user_id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid)));

CREATE POLICY tenants_for_jobs ON tenants
  FOR SELECT TO job_runner USING (status = 'active');

-- ===== persons
CREATE POLICY persons_provisioner_select ON persons
  FOR SELECT TO provisioner
  USING (true);

CREATE POLICY persons_provisioner_insert ON persons
  FOR INSERT TO provisioner
  WITH CHECK (true);

CREATE POLICY person_self ON persons
  FOR SELECT TO app_user
  USING (EXISTS (
    SELECT 1 FROM users u
    WHERE u.person_id = persons.id
      AND u.id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid)));

CREATE POLICY person_visible_via_membership ON persons
  FOR SELECT TO app_user
  USING (EXISTS (
    SELECT 1 FROM users u
    JOIN memberships m ON m.user_id = u.id
    WHERE u.person_id = persons.id
      AND m.tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  ));

-- ===== users
CREATE POLICY users_provisioner_select ON users
  FOR SELECT TO provisioner
  USING (true);

CREATE POLICY users_provisioner_insert ON users
  FOR INSERT TO provisioner
  WITH CHECK (true);

CREATE POLICY users_authenticator_read ON users
  FOR SELECT TO authenticator
  USING (true);

CREATE POLICY user_self_read ON users
  FOR SELECT TO app_user
  USING (id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid));

CREATE POLICY user_self_update ON users
  FOR UPDATE TO app_user
  USING (id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid))
  WITH CHECK (id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid));

CREATE POLICY user_visible_via_membership ON users
  FOR SELECT TO app_user
  USING (EXISTS (
    SELECT 1 FROM memberships m
    WHERE m.user_id = users.id
      AND m.tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  ));

-- ===== user_password_credentials
CREATE POLICY user_password_credentials_provisioner_insert ON user_password_credentials
  FOR INSERT TO provisioner
  WITH CHECK (true);

CREATE POLICY user_password_credentials_authenticator_read ON user_password_credentials
  FOR SELECT TO authenticator
  USING (true);

CREATE POLICY password_self_update ON user_password_credentials
  FOR UPDATE TO app_user
  USING (user_id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid))
  WITH CHECK (user_id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid));

-- ===== memberships
CREATE POLICY memberships_provisioner_select ON memberships
  FOR SELECT TO provisioner
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY memberships_provisioner_insert ON memberships
  FOR INSERT TO provisioner
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY membership_self ON memberships
  FOR SELECT TO app_user
  USING (user_id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid));

CREATE POLICY membership_tenant_read ON memberships
  FOR SELECT TO app_user
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY membership_tenant_update ON memberships
  FOR UPDATE TO app_user
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid))
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY membership_self_leave ON memberships
  FOR UPDATE TO app_user
  USING (user_id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid))
  WITH CHECK (user_id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid));

-- ===== membership_roles
CREATE POLICY membership_roles_provisioner_insert ON membership_roles
  FOR INSERT TO provisioner
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

-- ===== invitations
CREATE POLICY invitations_provisioner_select ON invitations
  FOR SELECT TO provisioner
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY invitations_provisioner_update ON invitations
  FOR UPDATE TO provisioner
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid))
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY invitations_tenant_read ON invitations
  FOR SELECT TO app_user
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY invitations_insert ON invitations
  FOR INSERT TO app_user
  WITH CHECK (
    tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    AND invited_by = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid)
    AND (intended_scope_mode = 'assigned'
         OR COALESCE((SELECT NULLIF(current_setting('app.can_manage_scope', true), '')::boolean), false)));

CREATE POLICY invitations_tenant_update ON invitations
  FOR UPDATE TO app_user
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid))
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

-- ===== auth_attempts
CREATE POLICY auth_attempts_authenticator_read ON auth_attempts
  FOR SELECT TO authenticator
  USING (true);

CREATE POLICY auth_attempts_authenticator_insert ON auth_attempts
  FOR INSERT TO authenticator
  WITH CHECK (true);

-- ===== membership_scope
CREATE POLICY membership_scope_provisioner_insert ON membership_scope
  FOR INSERT TO provisioner
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY membership_scope_read ON membership_scope
  FOR SELECT TO app_user
  USING (
    tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    AND (COALESCE((SELECT NULLIF(current_setting('app.can_manage_scope', true), '')::boolean), false)
         OR membership_id = (SELECT NULLIF(current_setting('app.membership_id', true), '')::uuid)));

CREATE POLICY membership_scope_admin_update ON membership_scope
  FOR UPDATE TO app_user
  USING (
    tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    AND COALESCE((SELECT NULLIF(current_setting('app.can_manage_scope', true), '')::boolean), false)
    AND membership_id <> (SELECT NULLIF(current_setting('app.membership_id', true), '')::uuid))
  WITH CHECK (
    tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    AND COALESCE((SELECT NULLIF(current_setting('app.can_manage_scope', true), '')::boolean), false)
    AND membership_id <> (SELECT NULLIF(current_setting('app.membership_id', true), '')::uuid));

-- ===== scope_assignments
CREATE POLICY scope_assignment_read ON scope_assignments
  FOR SELECT TO app_user
  USING (
    tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    AND (COALESCE((SELECT NULLIF(current_setting('app.can_manage_scope', true), '')::boolean), false)
         OR membership_id = (SELECT NULLIF(current_setting('app.membership_id', true), '')::uuid)));

CREATE POLICY scope_assignment_insert ON scope_assignments
  FOR INSERT TO app_user
  WITH CHECK (
    tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    AND COALESCE((SELECT NULLIF(current_setting('app.can_manage_scope', true), '')::boolean), false));

CREATE POLICY scope_assignment_update ON scope_assignments
  FOR UPDATE TO app_user
  USING (
    tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    AND COALESCE((SELECT NULLIF(current_setting('app.can_manage_scope', true), '')::boolean), false))
  WITH CHECK (
    tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    AND COALESCE((SELECT NULLIF(current_setting('app.can_manage_scope', true), '')::boolean), false));

-- ===== membership_auth
CREATE POLICY membership_auth_provisioner_insert ON membership_auth
  FOR INSERT TO provisioner
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY membership_auth_authenticator_read ON membership_auth
  FOR SELECT TO authenticator
  USING (true);

CREATE POLICY membership_auth_self_read ON membership_auth
  FOR SELECT TO app_user
  USING (EXISTS (
    SELECT 1 FROM memberships m
    WHERE m.id = membership_auth.membership_id
      AND m.user_id = (SELECT NULLIF(current_setting('app.user_id', true), '')::uuid)));

-- ===== modules
CREATE POLICY modules_read ON modules
  FOR SELECT TO app_user, provisioner
  USING (true);

-- ===== permissions
CREATE POLICY permissions_read ON permissions
  FOR SELECT TO app_user, provisioner
  USING (true);

-- ===== tenant_modules
CREATE POLICY tenant_modules_provisioner_insert ON tenant_modules
  FOR INSERT TO provisioner
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

-- ===== roles
CREATE POLICY roles_provisioner_select ON roles
  FOR SELECT TO provisioner
  USING (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY roles_provisioner_insert ON roles
  FOR INSERT TO provisioner
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
              AND is_system);

CREATE POLICY system_role_guard_update ON roles
  AS RESTRICTIVE FOR UPDATE TO app_user
  USING (NOT is_system)         -- no editing a system role
  WITH CHECK (NOT is_system);   -- and no promoting an ordinary role to system

CREATE POLICY system_role_guard_delete ON roles
  AS RESTRICTIVE FOR DELETE TO app_user
  USING (NOT is_system);        -- no deleting a system role

CREATE POLICY system_role_guard_insert ON roles
  AS RESTRICTIVE FOR INSERT TO app_user
  WITH CHECK (NOT is_system);   -- and no inserting a role flagged as system

-- ===== role_permissions
CREATE POLICY role_permissions_provisioner_insert ON role_permissions
  FOR INSERT TO provisioner
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

-- ===== role_templates
CREATE POLICY role_templates_provisioner_read ON role_templates
  FOR SELECT TO provisioner
  USING (true);

-- ===== role_template_permissions
CREATE POLICY role_template_permissions_provisioner_read ON role_template_permissions
  FOR SELECT TO provisioner
  USING (true);

-- ===== audit_log
CREATE POLICY audit_log_provisioner_insert ON audit_log
  FOR INSERT TO provisioner
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY audit_log_insert ON audit_log
  FOR INSERT TO app_user
  WITH CHECK (tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid));

CREATE POLICY audit_read ON audit_log
  FOR SELECT TO app_user
  USING (
    tenant_id = (SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    AND COALESCE((SELECT NULLIF(current_setting('app.scope_all', true), '')::boolean), false));

