using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql;

namespace Core.WhiteBoxTests;

// PLATFORM_CORE v1.14 §3.7 Test 28 [W] — no value generated by the database or by EF, and forgetting is
// loud — on its three sides. An acceptance criterion of T2 under rule 8 (PROOF_SPEC v1.1 does not list it).
[Collection(WhiteBoxCollection.Name)]
public class T2_Test28(WhiteBoxFixture fixture)
{
    // (a) The database: three catalog queries, all empty on the schema.
    private const string DefaultsQuery = """
        SELECT c.relname || '.' || a.attname
        FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p') AND a.attnum > 0 AND NOT a.attisdropped
          AND (a.atthasdef OR a.attidentity <> '' OR a.attgenerated <> '')
        """;
    private const string KeysQuery = """
        SELECT c.relname || '.' || a.attname
        FROM pg_index i JOIN pg_class c ON c.oid = i.indrelid JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ANY (i.indkey)
        WHERE i.indisprimary AND n.nspname = 'public' AND a.atttypid <> 'app_id'::regtype
        """;
    private const string TimestampsQuery = """
        SELECT c.relname || '.' || a.attname
        FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p') AND a.attnum > 0 AND NOT a.attisdropped
          AND a.attnotnull AND a.atttypid = 'timestamptz'::regtype
        """;

    [Fact]
    public async Task Test28a_Database_NoDefaults_KeysAreAppId_NotNullTimestampsAreAppTs()
    {
        await using var connection = new NpgsqlConnection(fixture.MigratorConnectionString);
        await connection.OpenAsync();

        Assert.Empty(await RowsAsync(connection, null, DefaultsQuery));
        Assert.Empty(await RowsAsync(connection, null, KeysQuery));
        Assert.Empty(await RowsAsync(connection, null, TimestampsQuery));
    }

    [Fact]
    public async Task Test28a_EachQuery_FailsOnAPlantedTable()
    {
        await using var connection = new NpgsqlConnection(fixture.MigratorConnectionString);
        await connection.OpenAsync();
        await using var transaction = await connection.BeginTransactionAsync();
        await using (var plant = new NpgsqlCommand(
            "CREATE TABLE t28_planted (id uuid PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now())", connection, transaction))
            await plant.ExecuteNonQueryAsync();

        Assert.Contains("t28_planted.created_at", await RowsAsync(connection, transaction, DefaultsQuery));
        Assert.Contains("t28_planted.id", await RowsAsync(connection, transaction, KeysQuery));
        Assert.Contains("t28_planted.created_at", await RowsAsync(connection, transaction, TimestampsQuery));
        await transaction.RollbackAsync();
    }

    // (b) The model: every property of every EF entity has ValueGenerated == Never.
    [Fact]
    public async Task Test28b_Model_EveryPropertyIsValueGeneratedNever()
    {
        await using var dataSource = fixture.CreateAppUserDataSource();
        await using var db = WhiteBoxFixture.Context(dataSource);

        var entities = db.Model.GetEntityTypes().ToList();
        var generated = entities
            .SelectMany(e => e.GetProperties().Select(p => (Table: e.GetTableName(), Column: p.GetColumnName(), p.ValueGenerated)))
            .Where(p => p.ValueGenerated != ValueGenerated.Never)
            .Select(p => $"{p.Table}.{p.Column} = {p.ValueGenerated}")
            .ToList();

        Assert.Equal(19, entities.Count);
        Assert.Empty(generated);
    }

    // (c) The behavior, through real EF commands: a Guid.Empty key → 23514 (app_id_check); a timestamp
    // left at its default → 23514 (app_ts_check); nothing saved.
    [Fact]
    public async Task Test28c_ForgottenKey_IsLoud_NothingSaved()
    {
        var action = "t28-forgotten-key-" + Guid.CreateVersion7();
        var error = await SaveAuditAsync(new AuditEntry
        {
            Id = default, TenantId = fixture.W1, ActorType = "test", Action = action, EntityType = "test", CreatedAt = DateTime.UtcNow,
        });

        Assert.Equal(PostgresErrorCodes.CheckViolation, error.SqlState);
        Assert.Equal("app_id_check", error.ConstraintName);
        Assert.Equal(0, await fixture.CountAsMigratorAsync("SELECT count(*) FROM audit_log WHERE action = @a", ("a", action)));
    }

    [Fact]
    public async Task Test28c_ForgottenTimestamp_IsLoud_NothingSaved()
    {
        var action = "t28-forgotten-timestamp-" + Guid.CreateVersion7();
        var error = await SaveAuditAsync(new AuditEntry
        {
            Id = Guid.CreateVersion7(), TenantId = fixture.W1, ActorType = "test", Action = action, EntityType = "test", CreatedAt = default,
        });

        Assert.Equal(PostgresErrorCodes.CheckViolation, error.SqlState);
        Assert.Equal("app_ts_check", error.ConstraintName);
        Assert.Equal(0, await fixture.CountAsMigratorAsync("SELECT count(*) FROM audit_log WHERE action = @a", ("a", action)));
    }

    // (c) And no command containing RETURNING: one row of every entity type, inserted through EF.
    // (The full bootstrap path is built in T4; its zero-RETURNING run belongs there. Here every entity
    // type's INSERT is covered, as migrator in a transaction that is rolled back.)
    [Fact]
    public async Task Test28c_EveryEntityTypeInsert_SendsNoReturning()
    {
        await using var dataSource = fixture.CreateMigratorDataSource();
        var recorder = new CommandRecorder();
        await using var db = WhiteBoxFixture.Context(dataSource, recorder);
        await using var transaction = await db.Database.BeginTransactionAsync();
        var now = DateTime.UtcNow;
        Guid Id() => Guid.CreateVersion7();

        var tenant = new Tenant { Id = Id(), Name = "Test 28", Status = "active", CreatedAt = now };
        var person = new Person { Id = Id(), FullName = "Test 28", Email = $"t28-{Guid.CreateVersion7():N}@test", CreatedAt = now };
        var module = new Module { Id = Id(), Code = "t28", NameAr = "x", NameEn = "x", DisplayOrder = 99, IsActive = true };
        var template = new RoleTemplate { Id = Id(), Code = "t28-template", NameAr = "x", NameEn = "x" };
        db.AddRange(tenant, person, module, template);
        await db.SaveChangesAsync();

        var user = new User { Id = Id(), PersonId = person.Id, UserType = "employee", Username = $"t28-{Guid.CreateVersion7():N}", Status = "active" };
        var role = new Role { Id = Id(), TenantId = tenant.Id, Code = "t28", NameAr = "x", NameEn = "x", IsActive = true };
        var permission = new Permission { Id = Id(), ModuleId = module.Id, Code = "t28.permission", NameAr = "x", NameEn = "x" };
        db.AddRange(user, role, permission);
        await db.SaveChangesAsync();

        var membership = new Membership { Id = Id(), TenantId = tenant.Id, UserId = user.Id, Status = "active", CreatedAt = now };
        db.AddRange(
            new UserPasswordCredential { UserId = user.Id, PasswordHash = "x", UpdatedAt = now },
            membership,
            new TenantModule { Id = Id(), TenantId = tenant.Id, ModuleId = module.Id, IsActive = true },
            new RolePermission { Id = Id(), TenantId = tenant.Id, RoleId = role.Id, PermissionId = permission.Id },
            new RoleTemplatePermission { TemplateId = template.Id, PermissionId = permission.Id },
            new Invitation
            {
                Id = Id(), TenantId = tenant.Id, Email = "x@test", RoleId = role.Id, TokenHash = "x", Status = "pending",
                InvitedBy = user.Id, ExpiresAt = now.AddDays(7), CreatedAt = now, IntendedScopeMode = "assigned",
            },
            new AuthAttempt { Id = Id(), UsernameEntered = "x", Succeeded = false, CreatedAt = now });
        await db.SaveChangesAsync();

        db.AddRange(
            new MembershipRole { Id = Id(), TenantId = tenant.Id, MembershipId = membership.Id, RoleId = role.Id },
            new MembershipScope { Id = Id(), TenantId = tenant.Id, MembershipId = membership.Id, ScopeMode = "all", UpdatedAt = now },
            new ScopeAssignment
            {
                Id = Id(), TenantId = tenant.Id, MembershipId = membership.Id, ScopeRefId = Id(), AssignmentRole = "contributor",
                Active = true, GrantedBy = user.Id, GrantedAt = now,
            },
            new MembershipAuth { Id = Id(), TenantId = tenant.Id, MembershipId = membership.Id, Provider = "password" },
            new AuditEntry { Id = Id(), TenantId = tenant.Id, ActorType = "test", Action = "t28", EntityType = "test", CreatedAt = now });
        await db.SaveChangesAsync();
        await transaction.RollbackAsync();

        var inserts = recorder.Commands.Where(c => c.Contains("INSERT INTO", StringComparison.OrdinalIgnoreCase)).ToList();
        var tablesInserted = db.Model.GetEntityTypes().Select(e => e.GetTableName()!)
            .Where(t => inserts.Any(c => c.Contains($"INSERT INTO {t} ", StringComparison.Ordinal))).ToList();
        Assert.Equal(19, tablesInserted.Count);
        Assert.DoesNotContain(recorder.Commands, c => c.Contains("RETURNING", StringComparison.OrdinalIgnoreCase));
    }

    private async Task<PostgresException> SaveAuditAsync(AuditEntry entry)
    {
        await using var dataSource = fixture.CreateAppUserDataSource();
        await using var db = WhiteBoxFixture.Context(dataSource);
        var error = await Assert.ThrowsAnyAsync<Exception>(() =>
            UnitOfWork.RunAsync(db, new SessionContext(Guid.CreateVersion7(), fixture.W1), async (context, ct) =>
            {
                await context.Database.ExecuteSqlRawAsync("SET LOCAL app.scope_all = 'true'", ct);
                context.AuditLog.Add(entry);
                await context.SaveChangesAsync(ct);
            }));
        for (var e = error; e is not null; e = e.InnerException)
            if (e is PostgresException pg)
                return pg;
        throw new Xunit.Sdk.XunitException($"Expected a PostgreSQL error, got {error.GetType().Name}: {error.Message}");
    }

    private static async Task<List<string>> RowsAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, string sql)
    {
        await using var command = new NpgsqlCommand(sql, connection, transaction);
        var rows = new List<string>();
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
            rows.Add(reader.GetString(0));
        return rows;
    }
}
