using System.Text.RegularExpressions;
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Core;

public class CoreDbContext : DbContext
{
    public CoreDbContext(DbContextOptions<CoreDbContext> options) : this((DbContextOptions)options)
    {
    }

    protected CoreDbContext(DbContextOptions options) : base(options)
    {
        // SaveChanges must not open a transaction of its own: outside the unit of work its
        // commands run with none, and the interceptor throws (3.5, T1.1).
        Database.AutoTransactionBehavior = AutoTransactionBehavior.Never;
    }

    public DbSet<Tenant> Tenants => Set<Tenant>();
    public DbSet<Person> Persons => Set<Person>();
    public DbSet<User> Users => Set<User>();
    public DbSet<UserPasswordCredential> UserPasswordCredentials => Set<UserPasswordCredential>();
    public DbSet<Membership> Memberships => Set<Membership>();
    public DbSet<MembershipRole> MembershipRoles => Set<MembershipRole>();
    public DbSet<Invitation> Invitations => Set<Invitation>();
    public DbSet<AuthAttempt> AuthAttempts => Set<AuthAttempt>();
    public DbSet<MembershipScope> MembershipScopes => Set<MembershipScope>();
    public DbSet<ScopeAssignment> ScopeAssignments => Set<ScopeAssignment>();
    public DbSet<MembershipAuth> MembershipAuths => Set<MembershipAuth>();
    public DbSet<Module> Modules => Set<Module>();
    public DbSet<Permission> Permissions => Set<Permission>();
    public DbSet<TenantModule> TenantModules => Set<TenantModule>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<RolePermission> RolePermissions => Set<RolePermission>();
    public DbSet<RoleTemplate> RoleTemplates => Set<RoleTemplate>();
    public DbSet<RoleTemplatePermission> RoleTemplatePermissions => Set<RoleTemplatePermission>();
    public DbSet<AuditEntry> AuditLog => Set<AuditEntry>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tenant>().ToTable("tenants");
        modelBuilder.Entity<Person>().ToTable("persons");
        modelBuilder.Entity<User>().ToTable("users");
        modelBuilder.Entity<UserPasswordCredential>().ToTable("user_password_credentials").HasKey(x => x.UserId);
        modelBuilder.Entity<Membership>().ToTable("memberships");
        modelBuilder.Entity<MembershipRole>().ToTable("membership_roles");
        modelBuilder.Entity<Invitation>().ToTable("invitations");
        modelBuilder.Entity<AuthAttempt>().ToTable("auth_attempts");
        modelBuilder.Entity<MembershipScope>().ToTable("membership_scope");
        modelBuilder.Entity<ScopeAssignment>().ToTable("scope_assignments");
        modelBuilder.Entity<MembershipAuth>().ToTable("membership_auth").Property(x => x.ProviderConfig).HasColumnType("jsonb");
        modelBuilder.Entity<Module>().ToTable("modules");
        modelBuilder.Entity<Permission>().ToTable("permissions");
        modelBuilder.Entity<TenantModule>().ToTable("tenant_modules");
        modelBuilder.Entity<Role>().ToTable("roles");
        modelBuilder.Entity<RolePermission>().ToTable("role_permissions");
        modelBuilder.Entity<RoleTemplate>().ToTable("role_templates");
        modelBuilder.Entity<RoleTemplatePermission>().ToTable("role_template_permissions").HasKey(x => new { x.TemplateId, x.PermissionId });
        modelBuilder.Entity<AuditEntry>(audit =>
        {
            audit.ToTable("audit_log");
            audit.Property(x => x.OldValue).HasColumnType("jsonb");
            audit.Property(x => x.NewValue).HasColumnType("jsonb");
        });

        foreach (var entity in modelBuilder.Model.GetEntityTypes())
        foreach (var property in entity.GetProperties())
        {
            property.SetColumnName(SnakeCase(property.Name));
            // Nothing generated by the database or by EF: no RETURNING in any command (§2, Test 28).
            property.ValueGenerated = ValueGenerated.Never;
        }
    }

    private static string SnakeCase(string name) => Regex.Replace(name, "(?<!^)([A-Z])", "_$1").ToLowerInvariant();
}
